### ISSUE TITLE
Webpush url

### ISSUE THREAD

**Issue by EIKSEU** [bartbutenaers/node-red-contrib-ui-web-push#9]
Hello, Thanks for the Nodered node works 👍. My problem is that the URL is not called correctly after clicking on the received message. I have the dashboard via a reserve proxy with ssl. The URL is https://domain, but it calls http://domain/ui can I change the setting?
 thank you mfg

**Comment by bartbutenaers** [comment]
Hi @EIKSEU,
Sorry for the delay!  Seems I had 2 issues in this repo, but I got no notifications about them.
I am currently finalizing a new completely new implementation of this node for the new Node-RED VueJs dashboard 2.0.
That node works completely different from this one.
Since I have very few free time lately, I won't be able to support this old node anymore.
My apologies!
Bart
